services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: pagamentos
    ports:
      - "27239:27017"
    networks:
      - pagamentos-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - pagamentos-network

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=picpay-pagamentos
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    networks:
      - pagamentos-network


networks:
  pagamentos-network:
    driver: bridge